import express from 'express';

const router = express.Router();

router.get('/', async (req, res) => {
  return res.status(200).send({
    data: [
  {
    "_id": {
      "$oid": "5eb3d25e0e3b4f2cf8f8a941"
    },
    "name": "AykutArslantau015f",
    "email": "aykut@sahratelekom.com",
    "phone": "905075771626",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-07"
  },
  {
    "_id": {
      "$oid": "5eb3d3446fb85c5b415527d6"
    },
    "name": "Muratu00c7eliktau015f",
    "email": "",
    "phone": "905326810764",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-07"
  },
  {
    "_id": {
      "$oid": "5eb400bf6fb85c390c5f1502"
    },
    "name": "Mustafam",
    "email": "mustafa@sahratelekom.com",
    "work_place": "",
    "phone": "905052349720",
    "process": "",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-07"
  },
  {
    "_id": {
      "$oid": "5eb44cde6fb85c63dcc71353"
    },
    "name": "Kubilayu00c7au011fru0131YILDIRIM",
    "email": "kubilay@tedankara.k12.tr",
    "phone": "905547657788",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-05-07"
  },
  {
    "_id": {
      "$oid": "5eb2b8176fb85c0e8e2d462b"
    },
    "name": "Mahmut",
    "email": "mkorkmaz@incirsigorta.com.tr",
    "phone": "905375552001",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-05-06"
  },
  {
    "_id": {
      "$oid": "5eb2c09c6fb85c0e926ee85b"
    },
    "name": "u00d6zgu00fcr",
    "email": "ozgur980@gmail.com",
    "phone": "905322237725",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-05-06"
  },
  {
    "_id": {
      "$oid": "5eb053fb6fb85c4631b7259f"
    },
    "name": "YusufARAT",
    "email": "yuseatar@gmail.com",
    "work_place": "",
    "phone": "905423295223",
    "process": "u00fczerindeu00e7alu0131u015fu0131lu0131yor",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "sanalsantral",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "bireysel",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-04"
  },
  {
    "_id": {
      "$oid": "5eac1b856fb85c7eb56626a2"
    },
    "name": "YasinDalku0131lu0131u00e7",
    "email": "ysndlklc1234@gmail.com",
    "phone": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-01"
  },
  {
    "_id": {
      "$oid": "5eac244a6fb85c46e4314c8d"
    },
    "name": "MehmetAliMetin",
    "email": "mhmtlmetin@gmail.com",
    "phone": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-05-01"
  },
  {
    "_id": {
      "$oid": "5ea941bd6fb85c51297d7ef3"
    },
    "name": "u00c7ETu0130NKILINu00c7",
    "email": "exelift@gmail.com",
    "work_place": "",
    "phone": "905432170700",
    "process": "",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-29"
  },
  {
    "_id": {
      "$oid": "5ea985866fb85c4353928854"
    },
    "name": "FatihCem",
    "email": "fatali@datamarket.com.tr",
    "phone": "905327305432",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-29"
  },
  {
    "_id": {
      "$oid": "5ea985da6fb85c4350b24a75"
    },
    "name": "MehmetAu00c7AR",
    "email": "macar@datamarket.com.tr",
    "phone": "905327305432",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-29"
  },
  {
    "_id": {
      "$oid": "5ea7fc216fb85c61b33387e5"
    },
    "name": "MehmetKalkan",
    "email": "mehmetkalkan@farmart.com.tr",
    "work_place": "",
    "phone": "905422139531",
    "process": "",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-28"
  },
  {
    "_id": {
      "$oid": "5ea840c96fb85c235bede6ed"
    },
    "name": "TuncayER",
    "email": "ertncyer@gmail.com",
    "work_place": "",
    "phone": "905334691276",
    "process": "adaymu00fcu015fteri",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "faturalu0131",
    "firma_turu": "",
    "urun_hizmet": "sanalsantral",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-28"
  },
  {
    "_id": {
      "$oid": "5ea714846fb85c71261208c6"
    },
    "name": "BurakPau00e7al",
    "email": "burkii_10@hotmail.com",
    "work_place": "",
    "phone": "905537850517",
    "process": "evrakbekleniyor",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "1",
    "odeme_periyodu": "u00f6nu00f6demeli",
    "firma_turu": "alu0131cu0131",
    "urun_hizmet": "",
    "tarife": "heru015fey5lipaket",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "bireysel",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-27"
  },
  {
    "_id": {
      "$oid": "5ea6be706fb85c175fbfd994"
    },
    "name": "MesutUyar",
    "email": "uyar.mesut@gmail.com",
    "work_place": "",
    "phone": "905453772316",
    "process": "su00f6zleu015fme",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "1",
    "odeme_periyodu": "",
    "firma_turu": "alu0131cu0131",
    "urun_hizmet": "sanalsantral",
    "tarife": "heru015fey5lipaket",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "pasif",
    "dogum_tarihi": "",
    "abonelik_tipi": "bireysel",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-27"
  },
  {
    "_id": {
      "$oid": "5ea6afc86fb85c1760e708fd"
    },
    "name": "Osman",
    "email": "bnamso@yandex.com",
    "work_place": "",
    "phone": "905558885452",
    "process": "u00fczerindeu00e7alu0131u015fu0131lu0131yor",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "sahra",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-27"
  },
  {
    "_id": {
      "$oid": "5ea54eff6fb85c192cbe96ac"
    },
    "name": "Nizamettin",
    "email": "nizami1946@hotmail.com",
    "phone": "905437378322",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-26"
  },
  {
    "_id": {
      "$oid": "5ea557e66fb85c192a5f9310"
    },
    "name": "VeyselATAY",
    "email": "veyselatay@hotmail.com",
    "work_place": "",
    "phone": "905349270584",
    "process": "adaymu00fcu015fteri",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "sanalsantral",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-26"
  },
  {
    "_id": {
      "$oid": "5ea2af9f6fb85c047df07329"
    },
    "name": "DevrimDEMu0130REL",
    "email": "devrim@beril.com",
    "work_place": "",
    "phone": "905333226327",
    "process": "",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "aktif",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-24"
  },
  {
    "_id": {
      "$oid": "5ea1fea66fb85c6146acac96"
    },
    "name": "Onur",
    "email": "latomin30@gmail.com",
    "phone": "905386324786",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-23"
  },
  {
    "_id": {
      "$oid": "5ea00b3a6fb85c55075014a4"
    },
    "name": "u00c7u0130MSAu00c7u0130MENTOSANAYu0130VETu0130CARETA.u015e",
    "email": "i.tas@cimsa.com.tr",
    "phone": "905313739826",
    "process": "adaymu00fcu015fteri",
    "authorized": "u0130brahimOnurTau015f",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "alu0131cu0131",
    "urun_hizmet": "mobikob",
    "tarife": "",
    "currency": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-04-22"
  },
  {
    "_id": {
      "$oid": "5ea03fc66fb85c193b8c8f15"
    },
    "name": "MustafaCan",
    "email": "polas312@yandex.com",
    "work_place": "",
    "phone": "905373110537",
    "process": "mevcutmu00fcu015fteri",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "1",
    "odeme_periyodu": "u00f6nu00f6demeli",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "heru015fey5lipaket",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "bireysel",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-22"
  },
  {
    "_id": {
      "$oid": "5e9ecc796fb85c3e4c0721eb"
    },
    "name": "SonerEsinbay",
    "email": "sesinbay@hotmail.com",
    "work_place": "",
    "phone": "",
    "process": "",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-21"
  },
  {
    "_id": {
      "$oid": "5e9ecfb16fb85c3e55b161f5"
    },
    "name": "SezenBayrak",
    "email": "sezen@no94.com.tr",
    "phone": "905517313294",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-21"
  },
  {
    "_id": {
      "$oid": "5e9f17f96fb85c3e50d045b0"
    },
    "name": "",
    "email": "",
    "phone": "905398255423",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-21"
  },
  {
    "_id": {
      "$oid": "5e9f18276fb85c3e4c07251d"
    },
    "name": "u00c7etinKONUR",
    "email": "ilhannakliyat78@gmail.com",
    "phone": "905398255423",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-21"
  },
  {
    "_id": {
      "$oid": "5e9f1ae16fb85c3e541577a6"
    },
    "name": "u00dcmit",
    "email": "ddos1961@gmail.com",
    "phone": "905550884881",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-21"
  },
  {
    "_id": {
      "$oid": "5e9c9f076fb85c15a3cc3d2d"
    },
    "name": "EsatCAN",
    "email": "esatcanaydemir@outlook.com.tr",
    "phone": "905464701703",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-19"
  },
  {
    "_id": {
      "$oid": "5e998c106fb85c6df00b69fb"
    },
    "name": "PrintandSmile",
    "email": "info@printandsmile.com.tr",
    "phone": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-17"
  },
  {
    "_id": {
      "$oid": "5e9a7c476fb85c5a370f1147"
    },
    "name": "Cemal",
    "email": "cml3461@hotmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-17"
  },
  {
    "_id": {
      "$oid": "5e96d7606fb85c6eda59e75d"
    },
    "name": "Gu00fclhan",
    "email": "gulhanpekin@hotmail.com",
    "phone": "905058150897",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-15"
  },
  {
    "_id": {
      "$oid": "5e96fd496fb85c6edecbf405"
    },
    "name": "Mustafa",
    "email": "mustafa@as.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-15"
  },
  {
    "_id": {
      "$oid": "5e96fe696fb85c6ee1d886c6"
    },
    "name": "Habibo",
    "email": "krrkfjd@gmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-15"
  },
  {
    "_id": {
      "$oid": "5e9716706fb85c2d9ea980b5"
    },
    "name": "Fatih",
    "email": "fatihgul.servis@gmail.com",
    "work_place": "",
    "phone": "905316314182",
    "process": "evrakbekleniyor",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-15"
  },
  {
    "_id": {
      "$oid": "5e95a5fb6fb85c61b32f2426"
    },
    "name": "FatihMuu015ftu",
    "email": "",
    "phone": "905064496548",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-14"
  },
  {
    "_id": {
      "$oid": "5e95c7e76fb85c1aae0bec25"
    },
    "name": "BilgehanSu00d6NMEZSOY",
    "email": "bilgehansonmezsoy@incyazilim.com",
    "phone": "905423875371",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-14"
  },
  {
    "_id": {
      "$oid": "5e956f426fb85c5dd1dd2794"
    },
    "name": "BilalGAZOZ",
    "email": "a.bilalgazoz@gmail.com",
    "work_place": "",
    "phone": "905377255424",
    "process": "mevcutmu00fcu015fteri",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-14"
  },
  {
    "_id": {
      "$oid": "5e93399a6fb85c3670adb5d9"
    },
    "name": "Halil",
    "email": "",
    "phone": "905333716173",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-12"
  },
  {
    "_id": {
      "$oid": "5e8e14946fb85c4322677adc"
    },
    "name": "Eray",
    "email": "eray.yilmaz@ileripc.com",
    "phone": "905360334351",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-08"
  },
  {
    "_id": {
      "$oid": "5e8c268c6fb85c2b9f39113a"
    },
    "name": "ALPER",
    "email": "imbc.imbc@yandex.com",
    "phone": "905323319401",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-07"
  },
  {
    "_id": {
      "$oid": "5e8a77ca6fb85c638731a1e3"
    },
    "name": "Deniz",
    "email": "deniz_yvz1992@hotmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-05"
  },
  {
    "_id": {
      "$oid": "5e8628896fb85c71d5b3c992"
    },
    "name": "Hayrettin",
    "email": "",
    "phone": "905323855692",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-02"
  },
  {
    "_id": {
      "$oid": "5e848c566fb85c5fcad31965"
    },
    "name": "ibrahimsau011flam",
    "email": "",
    "phone": "905558745806",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-04-01"
  },
  {
    "_id": {
      "$oid": "5e848fd06fb85c5fc89868d7"
    },
    "name": "Zekeriya",
    "email": "ibrahim@kotonorme.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-01"
  },
  {
    "_id": {
      "$oid": "5e848ff96fb85c5fc7d7c6e4"
    },
    "name": "ZekeriyaSAu011eLAM",
    "email": "ibrahim@kotonorme.com",
    "phone": "905558745806",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-01"
  },
  {
    "_id": {
      "$oid": "5e8496be6fb85c5fcb9ab815"
    },
    "name": "Milen",
    "email": "milen29@gmail.com",
    "phone": "905355462406",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-04-01"
  },
  {
    "_id": {
      "$oid": "5e83b17c6fb85c29fba44ab7"
    },
    "name": "Umut",
    "email": "raptoqw19@gmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-31"
  },
  {
    "_id": {
      "$oid": "5e83b3156fb85c29fe7d42ae"
    },
    "name": "u0130lkay",
    "email": "ilkaysu@gmail.com",
    "phone": "905432061222",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-31"
  },
  {
    "_id": {
      "$oid": "5e7f11a86fb85c47c7aa30c5"
    },
    "name": "Osman",
    "email": "osmankoc27@hotmail.co",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-28"
  },
  {
    "_id": {
      "$oid": "5e7f11aa6fb85c47c52b2bbb"
    },
    "name": "Osman",
    "email": "osmankoc27@hotmail.com",
    "phone": "903426808000",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-28"
  },
  {
    "_id": {
      "$oid": "5e7f64446fb85c47c35d58dd"
    },
    "name": "The",
    "email": "info@souptr.com",
    "phone": "905446990046",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-28"
  },
  {
    "_id": {
      "$oid": "5e7f557f6fb85c47c9442520"
    },
    "name": "Nihatu00c7ALIu015eKAN",
    "email": "nihat@passionen.com.tr",
    "work_place": "",
    "phone": "905523187618",
    "process": "adaymu00fcu015fteri",
    "tckn": "",
    "departman": "",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "sanalsantral",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "currency": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "evet",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-03-28"
  },
  {
    "_id": {
      "$oid": "5e7bfbb56fb85c79fb1df47f"
    },
    "name": "Mert",
    "email": "guzelmert3535@gmail.com",
    "phone": "905362180142",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-25"
  },
  {
    "_id": {
      "$oid": "5e7a054a6fb85c2fde2cff85"
    },
    "name": "umut",
    "email": "",
    "work_place": "5dfcce536fb85c61ff898892",
    "phone": "905422345607",
    "process": "",
    "tckn": "",
    "departman": "destek",
    "vergi_no": "",
    "vergi_dairesi": "",
    "adres": "",
    "il": "",
    "ilce": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "tarifelerdeki_vergi": "",
    "para_birimi": "",
    "musteri_temsilcisi": "",
    "durum": "",
    "dogum_tarihi": "",
    "abonelik_tipi": "",
    "email_setting": "",
    "aktivasyon_tarihi": "",
    "property": "person",
    "tenant": "sahra",
    "create_date": "2020-03-24"
  },
  {
    "_id": {
      "$oid": "5e75f4586fb85c75eb446992"
    },
    "name": "Emre",
    "email": "ahmeeetbjk@gmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-21"
  },
  {
    "_id": {
      "$oid": "5e7649ea6fb85c75eb447118"
    },
    "name": "Onur",
    "email": "onurcan7073@gmail.com",
    "phone": "905522954040",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-21"
  },
  {
    "_id": {
      "$oid": "5e748b016fb85c02359db952"
    },
    "name": "u00c7etin",
    "email": "cetinbdk@hotmail.com",
    "phone": "905398373747",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-20"
  },
  {
    "_id": {
      "$oid": "5e74adeb6fb85c32a8f31a6d"
    },
    "name": "FundaGu00dcMu00dcu015eBOu011eA",
    "email": "funda.gumusboga@altis.com.tr",
    "phone": "905426259825",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-20"
  },
  {
    "_id": {
      "$oid": "5e754ce96fb85c32a1d4a89e"
    },
    "name": "EYYu00dcP",
    "email": "ceolifecenter@gmail.com",
    "phone": "905525311822",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-20"
  },
  {
    "_id": {
      "$oid": "5e73711b6fb85c52d3187ce9"
    },
    "name": "Semih",
    "email": "semihyasa33@icloud.com",
    "phone": "905512348601",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-19"
  },
  {
    "_id": {
      "$oid": "5e737e666fb85c52d2e58d65"
    },
    "name": "Seyfi",
    "email": "sarici@mgl.cc",
    "phone": "905304610107",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-19"
  },
  {
    "_id": {
      "$oid": "5e71e4d46fb85c40c6722a0f"
    },
    "name": "Beyazu0130NAN",
    "email": "trgy.6836@gmail.com",
    "phone": "905426259825",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-18"
  },
  {
    "_id": {
      "$oid": "5e72010b6fb85c562c66ca81"
    },
    "name": "Test",
    "email": "test@test.com",
    "phone": "905075697892",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-18"
  },
  {
    "_id": {
      "$oid": "5e72e2e76fb85c0c8ed2232d"
    },
    "name": "u00d6zlem",
    "email": "ozlemgulerer.tg@gmail.com",
    "phone": "905532333441",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-18"
  },
  {
    "_id": {
      "$oid": "5e70da066fb85c436fa87e2e"
    },
    "name": "Bau015fkentKurubuz",
    "email": "",
    "phone": "903123957884",
    "process": "",
    "authorized": "u0130brahimBey",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70db426fb85c436ca983db"
    },
    "name": "Kentmed-KentMedikal",
    "email": "kentmedikal06@gmail.com",
    "phone": "905427972942",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dbb16fb85c4369b234d4"
    },
    "name": "TubisanBilgisayar",
    "email": "u00a0info@tubisan.com",
    "phone": "904222380354",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dc486fb85c4368d7e7c7"
    },
    "name": "RBenerjisistemleri",
    "email": "rbenerjisistemleri@gmail.com",
    "phone": "903123107402",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dc996fb85c436ca98435"
    },
    "name": "SUNFETTEKSTu0130LSANAYu0130VETu0130CARETu00a0",
    "email": "",
    "phone": "905306881908",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dd276fb85c437053007d"
    },
    "name": "u0130lkeru0130letiu015fim",
    "email": "",
    "phone": "905334154690",
    "process": "",
    "authorized": "u0130lkerBey",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dd576fb85c4371d43321"
    },
    "name": "Kartekhavalu0131elaletleri",
    "email": "",
    "phone": "902163944579",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70ddad6fb85c4370530084"
    },
    "name": "medtechnomu00fchendislik",
    "email": "info@medtechno.net",
    "phone": "908508400530",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70dddf6fb85c4371d43326"
    },
    "name": "Oparaya.com",
    "email": "",
    "phone": "908506500929",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70de3a6fb85c436a306dbd"
    },
    "name": "ErenElektronik",
    "email": "",
    "phone": "903123124578",
    "process": "",
    "authorized": "ErdalBey",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70de826fb85c436a306dcf"
    },
    "name": "Gu00fcnau00e7Makine",
    "email": "",
    "phone": "905433630800",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70deb46fb85c436e4c82b0"
    },
    "name": "MucizeEvim",
    "email": "",
    "phone": "905379738838",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70df266fb85c436a306de6"
    },
    "name": "DoraPrintBasku0131Teknolojileri",
    "email": "",
    "phone": "902122174757",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70df8c6fb85c4369b23529"
    },
    "name": "Mu0130AFORMBASIMREKLAMVEMATBAA",
    "email": "",
    "phone": "905326776653",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e0516fb85c436a306e3b"
    },
    "name": "Ku0131rkau011fau00e7Bilgisayar",
    "email": "",
    "phone": "902365882222",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e0dc6fb85c436a306e50"
    },
    "name": "Cephaneiletiu015fim",
    "email": "alican.cesur@superonline.com",
    "phone": "905328288880",
    "process": "",
    "authorized": "AliCanCESUR",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e1226fb85c436e4c8310"
    },
    "name": "BetaReklamveMatbaa",
    "email": "",
    "phone": "905327494016",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e1846fb85c436ddee0f7"
    },
    "name": "Dalku0131ranlastik",
    "email": "dalkiran.murat@gmail.com",
    "phone": "905337780969",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e1da6fb85c4369b2359a"
    },
    "name": "MonoEsteKozmetik",
    "email": "bilgi@monoeste.com",
    "phone": "905072056666",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "aday",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e24d6fb85c4371d43393"
    },
    "name": "imajans",
    "email": "info@imajans.com.tr",
    "phone": "903124650090",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e28b6fb85c436e4c8349"
    },
    "name": "Kupiu00e7vedu0131u015fticaret",
    "email": "defaultpf@baldwin.com.tr",
    "phone": "902126711854",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e2d66fb85c436ca98539"
    },
    "name": "Sendealgelsin.com",
    "email": "",
    "phone": "905425065232",
    "process": "",
    "authorized": "Semihbey",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e3a96fb85c436ca98565"
    },
    "name": "EymenMedikal",
    "email": "info@eymenmed.com.tru00a0",
    "phone": "903523203009",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e4176fb85c436ddee179"
    },
    "name": "AsveraEvu00dcru00fcnleri",
    "email": "",
    "phone": "903325020303",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e45c6fb85c436a306ef1"
    },
    "name": "Yau011fmurOrganizasyon",
    "email": "",
    "phone": "905061494334",
    "process": "",
    "authorized": "Nilu00fcferHanu0131m",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e4956fb85c436e4c83ae"
    },
    "name": "Enucuzunualu0131n",
    "email": "",
    "phone": "905537230994",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e4b66fb85c4368d7e90f"
    },
    "name": "Dou011fanElektrik",
    "email": "",
    "phone": "902126646666",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e70e5036fb85c436a306f09"
    },
    "name": "BarkotYangu0131nGu00fcvenlikSis.Turz.u0130nu015f.Gu0131daSan.veTic.Ltd.u015eti.",
    "email": "",
    "phone": "902163944651",
    "process": "",
    "authorized": "",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "n11mu00fcu015fteriu0307siu0307",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e7101046fb85c436ca988e1"
    },
    "name": "u00d6nder",
    "email": "trgy.6836@gmail.com",
    "phone": "",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-17"
  },
  {
    "_id": {
      "$oid": "5e6f5c176fb85c3da5a106ab"
    },
    "name": "Yilmaztesisatticaret",
    "email": "",
    "phone": "905301191555",
    "process": "",
    "authorized": "Hu00fcseyinDu00fczgu00fcn",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f5db66fb85c3d9f02d301"
    },
    "name": "PolyesterPlastik",
    "email": "",
    "phone": "905347176789",
    "process": "",
    "authorized": "FethiUtkuAksoy",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f695f6fb85c3da1b01205"
    },
    "name": "Su-DeTesisatDou011falgaz",
    "email": "",
    "phone": "905076624750",
    "process": "",
    "authorized": "u00d6merKou00e7",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f6a786fb85c3da2d11831"
    },
    "name": "CasYapiu0130nu015faatLtdu015eti",
    "email": "",
    "phone": "905377188300",
    "process": "",
    "authorized": "SonatAkbaba",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f6c796fb85c3da405c0b2"
    },
    "name": "TeksenSuSayau00e7laru0131",
    "email": "",
    "phone": "905326219316",
    "process": "",
    "authorized": "CahitTaras",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "reddetti",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f6d3c6fb85c3da5a1098f"
    },
    "name": "u00c7etinTesisat",
    "email": "",
    "phone": "905325951407",
    "process": "",
    "authorized": "EmreToprakcu0131",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "tekrararanacak",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f70866fb85c3da058b254"
    },
    "name": "M.T.Yapu0131u0130nu015faatDekorasyon",
    "email": "",
    "phone": "905060268156",
    "process": "",
    "authorized": "HaticeKu00fcbraEvirgen",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f712d6fb85c3da3a1789c"
    },
    "name": "AkarsuTeknik",
    "email": "",
    "phone": "905352352513",
    "process": "",
    "authorized": "Hamitu00d6zaslan",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f71486fb85c3d9f02d4de"
    },
    "name": "Taru0131k",
    "email": "berkbicer58@gmail.com",
    "phone": "905340891974",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f71556fb85c3da1b012aa"
    },
    "name": "Dau011flarMimarlu0131kMu00fchendislik",
    "email": "",
    "phone": "905070026108",
    "process": "",
    "authorized": "TayyarYu0131ldu0131ru0131m",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f71846fb85c3da3a178a0"
    },
    "name": "u00d6zgu00fcr3D",
    "email": "",
    "phone": "905332588054",
    "process": "",
    "authorized": "AlicanKartal",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e6f71bc6fb85c3da5a109f7"
    },
    "name": "Zatiu0130u00e7mimarlu0131k",
    "email": "",
    "phone": "905308792991",
    "process": "",
    "authorized": "Enginu015eahin",
    "abonelik_tipi": "",
    "tckn": "",
    "vergi_no": "",
    "adres": "",
    "ilce": "",
    "il": "",
    "faturalandirma_periyodu": "",
    "odeme_periyodu": "",
    "firma_turu": "",
    "urun_hizmet": "",
    "tarife": "",
    "para_birimi": "",
    "tarifelerdeki_vergi": "",
    "musteri_temsilcisi": "ku00fcbra",
    "dogum_tarihi": "",
    "durum": "",
    "aktivasyon_tarihi": "",
    "email_markting_": "",
    "property": "company",
    "tenant": "sahra",
    "create_date": "2020-03-16"
  },
  {
    "_id": {
      "$oid": "5e5fa2d30e3b4f791090b887"
    },
    "name": "FethiATu0130K",
    "email": "fethi@sahratelekom.com",
    "phone": "905426259825",
    "type": "aday",
    "tenant": "sahra",
    "property": "person",
    "email_setting": "evet",
    "create_date": "2020-03-04",
    "process": "adaymu00fcu015fteri"
  }]
});
});

export const mockRouter = router;
